#  Copyright (c) 2019-2021, Arm Limited, All Rights Reserved
#  SPDX-License-Identifier: Apache-2.0
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  This file is part of Mbed TLS (https://www.trustedfirmware.org/projects/mbed-tls/)

name: Code Review Workflow

on:
  pull_request:
    types: [unlabeled, labeled]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Needs review
        if: >
          contains(github.event.pull_request.labels.*.name, 'needs review') &&
          !contains(github.event.pull_request.labels.*.name, 'needs work') &&
          !contains(github.event.pull_request.labels.*.name, 'do not merge') &&
          !contains(github.event.pull_request.labels.*.name, 'ready for merge')
        uses: alex-page/github-project-automation-plus@v0.1.1
        with:
          project: Mbed TLS test PRs
          column: Needs review
          repo-token: ${{ secrets.AUTOMATION_TEST_TOKEN }}
      - name: Needs work
        if: >
          (!contains(github.event.pull_request.labels.*.name, 'needs review') ||
          contains(github.event.pull_request.labels.*.name, 'needs work') ||
          contains(github.event.pull_request.labels.*.name, 'do not merge')) &&
          !contains(github.event.pull_request.labels.*.name, 'ready for merge')
        uses: alex-page/github-project-automation-plus@v0.1.1
        with:
          project: Mbed TLS test PRs
          column: Needs work
          repo-token: ${{ secrets.AUTOMATION_TEST_TOKEN }}
